apiVersion: apps/v1
kind: Deployment
metadata:
  name: siri-requester
spec:
  selector:
    matchLabels:
      app: siri-requester
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: siri-requester
    spec:
      nodeSelector:
        # this node's IP is allows on MOT side, so we must use it
        kubernetes.io/hostname: hasadna-worker1
      terminationGracePeriodSeconds: 30
      containers:
        - name: app
          image: {{ .Values.siriRequesterImage }}
          resources: {{ .Values.siriRequesterResources }}
          {{ if .Values.siriRequesterPauseForDebug }}
          command:
            - sh
            - -c
            - while true; do sleep 86400; done
          {{ end }}
          env:
            - name: OPEN_BUS_SIRI_STORAGE_ROOTPATH
              value: "/siri_requester_storage"
            # we connect to MOT directly from specific nodes whose IPs are allows in MOT, so we don't need the proxy
            # - name: OPEN_BUS_SSH_TUNNEL_PRIVATE_KEY_FILE
            #   value: "/ssh_tunnel_private_key/key"
          envFrom:
            - secretRef:
                name: {{ .Values.siriRequesterSecretName }}
          volumeMounts:
            - name: sirirequester
              mountPath: /siri_requester_storage
            # - name: sshtunnelsecret
            #   mountPath: /ssh_tunnel_private_key
        - name: health
          image: {{ .Values.siriRequesterImage }}
          resources: {{ .Values.siriRequesterHealthResources }}
          command: [open-bus-siri-requester, health-daemon-start]
          env:
            - name: OPEN_BUS_SIRI_STORAGE_ROOTPATH
              value: "/siri_requester_storage"
          volumeMounts:
            - name: sirirequester
              mountPath: /siri_requester_storage
      volumes:
        - name: sirirequester
          nfs:
            server: {{ .Values.nfsServer | quote }}
            path: {{ .Values.siriRequesterNfsPath | quote }}
        # - name: sshtunnelsecret
        #   secret:
        #     secretName: {{ .Values.sshTunnelSecretName }}
        #     defaultMode: 0400
