odata:
  enabled: true
  ckanDeploymentEnabled: true
  ckanResources: '{"requests": {"cpu": "400m", "memory": "1200Mi"}, "limits": {"memory": "2Gi"}}'
  dbResources: '{"requests": {"cpu": "100m", "memory": "300Mi"}, "limits": {"memory": "600Mi"}}'
  solrResources: '{"requests": {"cpu": "60m", "memory": "600Mi"}, "limits": {"memory": "1Gi"}}'
  ckanDbPersistentDiskName: odata-green-db
  nfsEnabled: true
  nfsGcePersistentDiskName: odata-green-nfs
  ckanDataNfsServer: "10.23.243.110"
  ckanSecretName: ckan-default-5-secrets
  envVarsSecretName: env-vars
#  dbNfsEnabled: true
#  ckanDbNfsServer: 10.104.143.63
  replicas: 2
  nfsPersistentVolumeName: odata-green-nfs-gcepd

  db:
    terminationGracePeriodSeconds: 30
    image: orihoch/hasadna-k8s-odata-db:11
    opsImage: orihoch/hasadna-k8s-odata-db-ops:11

  datastore:
    enabled: true
#    initialize: true
    terminationGracePeriodSeconds: 30
    image: orihoch/hasadna-k8s-odata-db:12
    opsImage: orihoch/hasadna-k8s-odata-db-ops:11
    resources: '{"requests": {"cpu": "100m", "memory": "300Mi"}, "limits": {"memory": "600Mi"}}'
    persistentDiskName: odata-green-datastore-db
    dbOps:
      enabled: true
      backup: "gs://odata-k8s-backups/production/datastore-db-dump-"
#      restore: "gs://odata-k8s-backups/production/datastore-db-dump-2018-09-25.datastore.dump"

  dbOps:
    enabled: true
    backup: "gs://odata-k8s-backups/production/ckan-db-dump-"
#    restore: "gs://odata-k8s-backups/production/ckan-db-dump-2018-08-26.ckan.dump"

  solrImage: orihoch/solr-ckan-2.8.1:3

  pipelines:
    # pipelines require a shared directory with the ckan server
    # this requires ckanDataNfsServer to be set as well
    enabled: true
    resources: '{"requests": {"cpu": "400m", "memory": "400Mi"}, "limits": {"memory": "800Mi"}}'

  siteUrl: https://www.odata.org.il
  siteTitle: מידע ממשלתי לעם
  siteLogo: /base/images/ckan-logo.png
  siteDescription: אתר זה מרכז מידע ממקורות ממשלתיים וציבוריים
  displayTimezone: Asia/Jerusalem
  favIcon: /base/images/ckan.ico
  localeDefault: he
  localeOrder: he en ar
  localesOffered: he en ar
  localesFilteredOut: ""
  ckanPlugins: >
    stats text_view image_view recline_view
    odata_org_il file_uploader_ui datapackage_pipelines upload_via_email
    datastore datapusher

  auth:
    anon_create_dataset: "false"
    create_unowned_dataset: "false"
    create_dataset_if_not_in_organization: "true"
    user_create_groups: "false"
    user_create_organizations: "false"
    user_delete_groups: "false"
    user_delete_organizations: "false"
    create_user_via_api: "false"
    create_user_via_web: "true"
    roles_that_cascade_to_sub_groups: "admin"
