odata:
  enabled: true
  ckanDeploymentEnabled: true
  ckanResources: '{"requests": {"cpu": "400m", "memory": "1200Mi"}, "limits": {"memory": "2Gi"}}'
  dbResources: '{"requests": {"cpu": "100m", "memory": "300Mi"}, "limits": {"memory": "600Mi"}}'
  solrResources: '{"requests": {"cpu": "60m", "memory": "600Mi"}, "limits": {"memory": "1Gi"}}'
  ckanDataPersistentDiskName: odata-ckan-data
  ckanDbPersistentDiskName: odata-db
  nfsEnabled: true
  nfsGcePersistentDiskName: odata-ckan-data-nfs
  ckanDataNfsServer: 10.23.252.189
  etcCkanDefaultSecretName: etc-ckan-default-7
#  dbNfsEnabled: true
#  ckanDbNfsServer: 10.104.143.63

  db:
    terminationGracePeriodSeconds: 30
    image: orihoch/hasadna-k8s-odata-db:11
    opsImage: orihoch/hasadna-k8s-odata-db-ops:11

  dbOps:
    enabled: true
    backup: "gs://odata-k8s-backups/production/ckan-db-dump-"
#    restore: "gs://odata-k8s-backups/production/ckan-db-dump-2018-08-26.ckan.dump"

  solrImage: orihoch/solr-ckan-2.8.1:3
