{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: etc-traefik
data:
  traefik.toml: |
    # https://docs.traefik.io/configuration/commons/

    debug = false

    defaultEntryPoints = ["http"{{ if .Values.letsencrypt.enabled }}, "https"{{ end }}]
    
    [entryPoints]
        [entryPoints.http]
        address = ":80"

        {{ if .Values.letsencrypt.enabled }}
        [entryPoints.https]
        address = ":443"
          [entryPoints.https.tls]
        {{ end }}

    {{ if .Values.letsencrypt.enabled }}
    [acme]
      email = {{ .Values.letsencrypt.acmeEmail | quote }}
      storage = "/traefik-acme/acme.json"
      entryPoint = "https"
      {{ if .Values.oknesset.enabled }}
{{ .Values.oknesset.acmeDomains | indent 6 }}
      {{ end }}
      [acme.dnsChallenge]
        provider = {{ .Values.letsencrypt.dnsProvider | quote }}
    {{ end }}

    [file]
    
    [backends]
      {{ if .Values.budgetkey.enabled }}
      [backends.budgetkeynginx]
        [backends.budgetkeynginx.servers.server1]
          url = {{ .Values.budgetkey.backendUrl | quote }}
      {{ end }}

      {{ if .Values.oknesset.enabled }}
      [backends.oknessetnginx]
        [backends.oknessetnginx.servers.server1]
          url = {{ .Values.oknesset.backendUrl | quote }}
      {{ end }}

    [frontends]
      {{ if .Values.budgetkey.enabled }}
      [frontends.budgetkeynginx]
        backend="budgetkeynginx"
        passHostHeader = true
        [frontends.budgetkeynginx.routes.route1]
          rule = {{ .Values.budgetkey.frontendRule | quote }}
      {{ end }}

      {{ if .Values.oknesset.enabled }}
      [frontends.oknessetnginx]
        backend="oknessetnginx"
        passHostHeader = true
        [frontends.oknessetnginx.routes.route1]
          rule = {{ .Values.oknesset.frontendRule | quote }}
      {{ end }}

{{ end }}
