{{ if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - {name: '80', port: 80}
  {{ if .Values.letsencrypt.enabled }}
  - {name: '443', port: 443}
  {{ end }}
  selector:
    app: traefik
  {{ if .Values.enableLoadBalancer }}
  type: LoadBalancer
  {{ if .Values.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancerIP | quote }}
  {{ end }}
  {{ end }}
{{ end }}
