enabled: true
ckanDgpDbNfsServer: "~iac:hasadna_nfs1_internal_ip~"
ckanDgpDbNfsPath: "/datacity/ckan-dgp-db"
ckanDgpLogsNfsServer: "~iac:hasadna_nfs1_internal_ip~"
ckanDgpLogsNfsPath: "/datacity/ckan-dgp-logs"
importer:
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/datacity/importer"
ingresses:
  - name: frontend
    rules:
      - host: app.datacity.org.il
        serviceName: importer
        servicePort: 5000
  - name: nominatim
    rules:
      - host: geocode.datacity.org.il
        serviceName: nominatim
        servicePort: 8080
  - name: tabula
    rules:
      - host: tabula.datacity.org.il
        serviceName: tabula
        servicePort: 9292
  - name: api
    rules:
      - host: api.datacity.org.il
        serviceName: api
        servicePort: 8000
  - name: ckan-dgp
    rules:
      - host: ckan-dgp.datacity.org.il
        serviceName: ckan-dgp
        servicePort: 5000
  - name: mapali
    rules:
      - host: mapali.datacity.org.il
        serviceName: mapali
        servicePort: 5000

vertical_pod_autoscalers:
- apiVersion: apps/v1
  kind: deployment
  name: api
- apiVersion: apps/v1
  kind: deployment
  name: db
- apiVersion: apps/v1
  kind: deployment
  name: importer
- apiVersion: apps/v1
  kind: deployment
  name: nominatim
- apiVersion: apps/v1
  kind: deployment
  name: tabula
