datacity:
  enabled: true
  importer:
    nfsServer: "172.16.0.2"
    nfsPath: "/srv/default2/datacity/importer"
  ingresses:
    - name: frontend
      rules:
        - host: app.datacity.org.il
          serviceName: importer
          servicePort: 5000
    - name: nominatim
      rules:
        - host: geocode.datacity.org.il
          serviceName: nominatim
          servicePort: 8080
    - name: api
      rules:
        - host: api.datacity.org.il
          serviceName: api
          servicePort: 8000
