enabled: true
nfsServer: "~iac:hasadna_nfs1_internal_ip~"
sshTunnelSecretName: sshtunnel

# siriRequesterPauseForDebug: true
siriRequesterResources: '{"requests": {"cpu": "200m", "memory": "1000Mi"}, "limits": {"memory": "1500Mi"}}'
siriRequesterNginxResources: '{"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}'
siriRequesterHealthResources: '{"requests": {"cpu": "50m", "memory": "100Mi"}, "limits": {"memory": "200Mi"}}'
siriRequesterNfsPath: "/openbus/siri-requester"
siriRequesterSecretName: siri-requester

siriEtlProcessNewSnapshotsResources: '{"requests": {"cpu": "3000m", "memory": "4000Mi"}, "limits": {"memory": "8000Mi"}}'

db:
  enabled: false
  # image is used for the stride-db-migrations, it should use the same version as the dedicated db uses
  image: "postgres:14"
  # resources: '{"requests": {"cpu": "6000m", "memory": "30000Mi"}, "limits": {"cpu": "6000m", "memory": "30000Mi"}}'
  # nfsServer: "172.16.0.12"
  # nfsPath: "/stride/db"
  # nodePort: 31834
  # backupSchedule: "37 1 * * *"
  # backupImage: "docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db-backup:d358f4dfa16e60f9aad8946cad314fa4b5a195cb"
  # backupResources: '{"requests": {"cpu": "200m", "memory": "1500Mi"}, "limits": {"cpu": "400m", "memory": "3000Mi"}}'

airflowHomeNfsPath: "/openbus/airflow-home"
airflowDb:
  image: "postgres:13"
  resources: '{"requests": {"cpu": "200m", "memory": "1000Mi"}, "limits": {"memory": "2000Mi"}}'
  nfsPath: "/openbus/airflow-db"
airflowWebserver:
  resources: '{"requests": {"cpu": "250m", "memory": "1000Mi"}, "limits": {"memory": "2000Mi"}}'
airflowScheduler:
  resources: '{"requests": {"cpu": "600m", "memory": "8000Mi"}, "limits": {"memory": "12000Mi"}}'

airflow:
  enableEmails: true
  AIRFLOW__SMTP__SMTP_MAIL_FROM: "Open Bus Airflow <open-bus-airflow@hasadna.org.il>"
  AIRFLOW__WEBSERVER__BASE_URL: "https://~iac:ingress-open-bus-airflow~"

strideApiResources: {"requests": {"cpu": "1000m", "memory": "1000Mi"}, "limits": {"memory": "2000Mi"}}

gtfsNfsPath: "/openbus/gtfs"

secrets:
  - name: sshtunnel
    data:
      key: "~vault:Projects/OBus/k8s-secrets:sshtunnel-key~"
  - name: siri-requester
    data:
      OPEN_BUS_MOT_KEY: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_MOT_KEY~"
      OPEN_BUS_S3_ACCESS_KEY_ID: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_S3_ACCESS_KEY_ID~"
      OPEN_BUS_S3_BUCKET: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_S3_BUCKET~"
      OPEN_BUS_S3_SECRET_ACCESS_KEY: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_S3_SECRET_ACCESS_KEY~"
      OPEN_BUS_SSH_TUNNEL_SERVER_IP: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_SSH_TUNNEL_SERVER_IP~"
  - name: db
    data:
      POSTGRES_PASSWORD: "~vault:Projects/OBus/k8s-secrets:DB_POSTGRES_PASSWORD~"
      SQLALCHEMY_URL: "~vault:Projects/OBus/k8s-secrets:DB_SQLALCHEMY_URL~"
  - name: airflow
    data:
      AIRFLOW__SMTP__SMTP_HOST: "~vault:Projects/OBus/k8s-secrets:AIRFLOW__SMTP__SMTP_HOST~"
      AIRFLOW__SMTP__SMTP_PASSWORD: "~vault:Projects/OBus/k8s-secrets:AIRFLOW__SMTP__SMTP_PASSWORD~"
      AIRFLOW__SMTP__SMTP_USER: "~vault:Projects/OBus/k8s-secrets:AIRFLOW__SMTP__SMTP_USER~"
      OPEN_BUS_PIPELINES_AIRFLOW_ADMIN_PASSWORD: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_PIPELINES_AIRFLOW_ADMIN_PASSWORD~"
      OPEN_BUS_PIPELINES_ALERT_EMAILS: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_PIPELINES_ALERT_EMAILS~"
      OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_ACCESS_KEY_ID~"
      OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY: "~vault:Projects/OBus/k8s-secrets:OPEN_BUS_STRIDE_PUBLIC_S3_WRITE_SECRET_ACCESS_KEY~"
  - name: airflow-db
    data:
      POSTGRES_PASSWORD: "~vault:Projects/OBus/k8s-secrets:AIRFLOW_DB_POSTGRES_PASSWORD~"
      SQLALCHEMY_URL: "~vault:Projects/OBus/k8s-secrets:AIRFLOW_DB_SQLALCHEMY_URL~"

ingresses:
  - name: siri-requester
    ssl: true
    rules:
      - host: "~iac:ingress-open-bus-siri-requester~"
        serviceName: siri-requester-nginx
        servicePort: 80
  - name: airflow-webserver
    ssl: true
    rules:
      - host: "~iac:ingress-open-bus-airflow~"
        serviceName: airflow-webserver
        servicePort: 8080
  - name: stride-api
    ssl: true
    rules:
      - host: "~iac:ingress-open-bus-stride-api~"
        serviceName: stride-api
        servicePort: 80
  - name: gtfs
    ssl: true
    rules:
      - host: "~iac:ingress-open-bus-gtfs-data~"
        serviceName: gtfs-nginx
        servicePort: 80
  - name: webmon
    ssl: true
    rules:
      - host: "~iac:ingress-open-bus-webmon~"
        serviceName: webmon
        servicePort: 8901
