enabled: true
botkit:
  enabled: true
  # persistent volume claim and disk names must be unique across all projects in the cluster
  # persistentVolumeClaimName: reportit-botkit-data
  # create the disk first:
  # gcloud compute disks create --size=20GB --zone=europe-west1-b openpension-mongodb-data
  # persistentVolumePersistentDiskName: reportit-botkit-data
  # persistentVolumeSize: 1G
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/reportit/botkit"
  resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "339Mi"}}'
strapi:
  enabled: true
  # persistent volume claim and disk names must be unique across all projects in the cluster
  # persistentVolumeClaimName: reportit-strapi-data
  # create the disk first:
  # gcloud compute disks create --size=500GB --zone=europe-west1-b reportit-strapi-data
  # persistentVolumePersistentDiskName: reportit-strapi-data
  # persistentVolumeSize: 500G
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/reportit/strapi"
  resources: '{"requests": {"cpu": "93m", "memory": "256Mi"}, "limits": {"cpu": "163m", "memory": "1119Mi"}}'
postgres:
  enabled: true
  # persistent volume claim and disk names must be unique across all projects in the cluster
  # persistentVolumeClaimName: reportit-strapi-db
  # create the disk first:
  # gcloud compute disks create --size=5GB --zone=europe-west1-b reportit-strapi-db
  # persistentVolumePersistentDiskName: reportit-strapi-db
  # persistentVolumeSize: 5G
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/reportit/postgres"
  resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "339Mi"}}'
ingresses:
  - name: botkit
    rules:
      - host: botkit-cms.obudget.org
        serviceName: botkit
        servicePort: 3000
  - name: strapi
    proxyBodySize: "200m"
    rules:
      - host: reportit-cms.obudget.org
        serviceName: strapi
        servicePort: 1337
      - host: cms.equality.org.il
        serviceName: strapi
        servicePort: 1337

vertical_pod_autoscalers:
- apiVersion: apps/v1
  kind: deployment
  name: botkit
- apiVersion: apps/v1
  kind: deployment
  name: postgres
- apiVersion: apps/v1
  kind: deployment
  name: strapi
