anyway:
  lint-environments: anyway
  automatic-updates:
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: anyway-main
      container-name: anyway
      image-prop: image
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: anyway-secondaries
      container-name: anyway
      image-prop: image
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: nginx
      container-name: nginx
      image-prop: nginxImage
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of anyway-report docker image
      namespace-name: anyway
      deployment-name: reports
      container-name: reports
      image-prop: anywayReportsImage
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of prod etl anyway
      namespace-name: anyway
      deployment-name: airflow-webserver
      container-name: webserver
      image-prop: airflowImage
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of prod etl anyway
      namespace-name: anyway
      deployment-name: airflow-scheduler
      container-name: scheduler
      image-prop: airflowImage
      kubeconfig: .rancher.kubeconfig
    - commit-message: automatic update of prod etl anyway
      namespace-name: anyway
      deployment-name: airflow-nginx
      container-name: nginx
      image-prop: etlNginxImage
      kubeconfig: .rancher.kubeconfig

anyway-dev:
  lint-environments: anyway-dev
  chart-name: anyway
  automatic-updates:
    - commit-message: automatic update of dev anyway
      namespace-name: anyway-dev
      deployment-name: anyway-main
      container-name: anyway
      image-prop: imageDev
      kubeconfig: .rancher.kubeconfig
      pre-deploy-update-chart-config-value: true
    - commit-message: automatic update of dev anyway
      namespace-name: anyway-dev
      deployment-name: nginx
      container-name: nginx
      image-prop: nginxImageDev
      kubeconfig: .rancher.kubeconfig
      pre-deploy-update-chart-config-value: true
    - commit-message: automatic update of dev etl anyway
      namespace-name: anyway-dev
      deployment-name: airflow-webserver
      container-name: webserver
      image-prop: airflowImageDev
      kubeconfig: .rancher.kubeconfig
      pre-deploy-update-chart-config-value: true
    - commit-message: automatic update of dev etl anyway
      namespace-name: anyway-dev
      deployment-name: airflow-scheduler
      container-name: scheduler
      image-prop: airflowImageDev
      kubeconfig: .rancher.kubeconfig
      pre-deploy-update-chart-config-value: true
    - commit-message: automatic update of dev etl anyway
      namespace-name: anyway-dev
      deployment-name: airflow-nginx
      container-name: nginx
      image-prop: etlNginxImageDev
      kubeconfig: .rancher.kubeconfig
      pre-deploy-update-chart-config-value: true

redash:
  lint-environments: redash
