odata:
  lint-environments: odata-kamatera
  automatic-update:
    commit-message: automatic update of odata-ckan
    namespace-name: odata
    deployment-name: ckan
    container-name: ckan
    image-prop: ckanImage
    kubeconfig: /.rancher.kubeconfig

avidcovider:
  lint-environments: avidcovider-gcloud
  automatic-updates:
    - commit-message: automatic update of avid-covider pipelines
      namespace-name: avidcovider
      deployment-name: pipelines
      container-name: pipelines
      image-prop: pipelinesImage

anyway:
  lint-environments: anyway
  automatic-updates:
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: anyway-main
      container-name: anyway
      image-prop: image
      kubeconfig: /.rancher.kubeconfig
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: anyway-secondaries
      container-name: anyway
      image-prop: image
      kubeconfig: /.rancher.kubeconfig
    - commit-message: automatic update of anyway
      namespace-name: anyway
      deployment-name: nginx
      container-name: nginx
      image-prop: nginxImage
      kubeconfig: /.rancher.kubeconfig

#mysadna:
#  automatic-update:
#    commit-message: automatic update of mysadna
#    namespace-name: mysadna
#    deployment-name: mysadna
#    container-name: mysadna

#openpension:
#  automatic-updates:
#    - commit-message: automatic update of openpension
#      namespace-name: openpension
#      deployment-name: server
#      container-name: server
#      image-prop: server image
#    - commit-message: automatic update of openpension
#      namespace-name: openpension
#      deployment-name: client
#      container-name: client
#      image-prop: client image
#
