anyway:
  automatic-update:
    commit-message: automatic update of anyway testing environment
    namespace-name: anyway
    deployment-name: anyway
    container-name: anyway

anyway-production:
  chart-name: anyway
  automatic-update:
    commit-message: automatic update of anyway production environment
    namespace-name: anyway-production
    deployment-name: anyway
    container-name: anyway
    image-prop: productionImage

odata:
  lint-environments: odata odata-minikube
  automatic-update:
    commit-message: automatic update of odata-ckan
    namespace-name: odata
    deployment-name: ckan
    container-name: ckan
    image-prop: ckanImage
