anyway:
  airflowImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:v0.0.25
  airflowImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:14b3e2595f1585a123d3c28b7a4dc025e30b2ed2
  anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-b456d8b
  dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-98f07c0
  dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-98f07c0
  etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
  etlNginxImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:v0.0.25
  etlNginxImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:14b3e2595f1585a123d3c28b7a4dc025e30b2ed2
  image: docker.pkg.github.com/hasadna/anyway/anyway:sha-98f07c0
  imageDev: docker.pkg.github.com/hasadna/anyway/anyway:sha-cd26789
  nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-98f07c0
  nginxImageDev: docker.pkg.github.com/hasadna/anyway/nginx:sha-cd26789
avidcovider:
  pipelinesImage: docker.pkg.github.com/hasadna/avid-covider-pipelines/pipelines:a32a5293d45c588859b28e8ecebcf4c7d1180cef
datacity:
  ckanDgpServerImage: docker.pkg.github.com/hasadna/datacity-ckan-dgp/server:4a61be492e5c72e56d3aa9caadee5315cd48f90b
  dgpAppDbImage: akariv/dgp-app-db@sha256:8ebf03009fb6c6e42308c2579b4ac2d979325a492fffd5942af0de3fc709ce28
  dgpAppImage: docker.pkg.github.com/hasadna/datacity-dgp-importer/server:4390a988da6a1f00972fd9be762b2afc20ce0d37
mysadna:
  image: uumpa/hasadna-mysadna:c0a681d5a0c68ada76b6d68fce1c2115224790a9
odata:
  ckanImage: ghcr.io/orihoch/data4dappl/odata-ckan:a00ae4862a3a92d51334aa4e2d441e20bbf368f9
oknesset:
  DataBackendImage: uumpa/knesset-data-backend:bc03d3c1830a856d6bbacf4b2481d83dd1f836c6
  WebUiImage: uumpa/knesset-data-web-ui:94b6de1cc89ae20647e35aa606c3c9b95e81dbe6
openbus:
  pipelinesImage: docker.pkg.github.com/hasadna/open-bus-pipelines/open-bus-pipelines:146d74cd851fcb855a5088a64858201d840aaa23
  siriEtlImage: docker.pkg.github.com/hasadna/open-bus-siri-etl/open-bus-siri-etl:92ff0b65c9aea401d7ed480b0b9c25f32a24c55d
  siriRequesterImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester:2ef13e4bf50261a41230b33a46ad76964ce6b7bf
  siriRequesterNginxImage: docker.pkg.github.com/hasadna/open-bus-siri-requester/open-bus-siri-requester-nginx:2ef13e4bf50261a41230b33a46ad76964ce6b7bf
  strideApiImage: ghcr.io/hasadna/open-bus-stride-api/open-bus-stride-api:b00efdcd64c405a5e5dc09d83d2fec3c2b3f93e1
  strideDbAppImage: docker.pkg.github.com/hasadna/open-bus-stride-db/open-bus-stride-db:2fcf21b99a0fab22a4ea8ec05ace3ef0cd1f4003
openpension:
  client:
    image: hasadna/open-pension-client:1f8f83e2a8e61e0928e4b5f499475f8e675265bd
  server:
    image: uumpa/hasadna-openpension:server-c72f525ec4d7de2e4337c0a7b0b1f6f8d357b72f
