archiveAppImage: ghcr.io/hasadna/openlaw-archive/openlaw-archive-app:81cdbf8a2436c92b377e58a6674a1ba92126dc4e
archiveNginxImage: ghcr.io/hasadna/openlaw-archive/openlaw-archive-nginx:81cdbf8a2436c92b377e58a6674a1ba92126dc4e
