archiveAppImage: ghcr.io/hasadna/openlaw-archive/openlaw-archive-app:6ac070484fb5776735a6a2fbabc326ebcf0b96eb
archiveNginxImage: ghcr.io/hasadna/openlaw-archive/openlaw-archive-nginx:6ac070484fb5776735a6a2fbabc326ebcf0b96eb
