enabled: true
importer:
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/treebase/importer"
ingresses:
  - name: frontend
    rules:
      - host: upload.digital-forest.org.il
        serviceName: importer
        servicePort: 5000
  - name: api
    rules:
      - host: api.digital-forest.org.il
        serviceName: api
        servicePort: 8000
db:
  # Pulled Jul 14, 2023
  # image: postgres:14@sha256:19c87e38a0b13def945579f5d8fcd68aadfd0060816ea6991cb009b7d8da0c89
  image: postgis/postgis:14-3.3@sha256:d7c09eb3597caecad34803ff8266ab7300f226da324c07fcec564325e311221c
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/treebase/db"
  resources:
    requests:
      cpu: 300m
      memory: 1000Mi
    limits:
      cpu: 7000m
      memory: 2000Mi

secrets:
  - name: db
    data:
      POSTGRES_PASSWORD: "~vault:Projects/treebase/k8s-secrets:POSTGRES_PASSWORD~"

vertical_pod_autoscalers:
- apiVersion: apps/v1
  kind: deployment
  name: api
- apiVersion: apps/v1
  kind: deployment
  name: db
- apiVersion: apps/v1
  kind: deployment
  name: importer
