enabled: true
importer:
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/treebase/importer"
ingresses:
  - name: frontend
    rules:
      - host: upload.digital-forest.org.il
        serviceName: importer
        servicePort: 5000
  - name: api
    rules:
      - host: api.digital-forest.org.il
        serviceName: api
        servicePort: 8000

vertical_pod_autoscalers:
- apiVersion: apps/v1
  kind: deployment
  name: api
- apiVersion: apps/v1
  kind: deployment
  name: db
- apiVersion: apps/v1
  kind: deployment
  name: importer
