apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        # Built from apps/hasadna-argocd/plugin Jun 16, 2022
        image: ghcr.io/hasadna/hasadna-k8s-argocd:a4396ec95d96f532b01dd5992364ef7e2f6e35af
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-hasadna-plugin
          subPath: argocd-hasadna-plugin
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]

        # Don't forget to update this to whatever the stable release version is
        # Note the lack of the `v` prefix unlike the git tag
        env:
          - name: AVP_VERSION
            value: "1.10.1"
        args:
          - >-
            wget -O argocd-hasadna-plugin
            https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps/hasadna-argocd/argocd-hasadna-plugin.py &&
            chmod +x argocd-hasadna-plugin &&
            mv argocd-hasadna-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      automountServiceAccountToken: true
      serviceAccountName: argocd-server
