apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        # Built from apps/hasadna-argocd/plugin Jun 16, 2022
        image: ghcr.io/hasadna/hasadna-k8s-argocd:9e673f3920177061eb2158ffb61ca6f85f68d4a3@sha256:e2fd5eab4be999f98decd5807a2c25e0b9cbd2308d71fffc50c213adaf7fce4f
        volumeMounts:
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-vault-plugin
          subPath: argocd-vault-plugin
        - name: custom-tools
          mountPath: /usr/local/bin/argocd-hasadna-plugin
          subPath: argocd-hasadna-plugin
        envFrom:
          - secretRef:
              name: argocd-vault-plugin-credentials
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alpine:3.8
        command: [sh, -c]

        # Don't forget to update this to whatever the stable release version is
        # Note the lack of the `v` prefix unlike the git tag
        env:
          - name: AVP_VERSION
            value: "1.10.1"
        args:
          - >-
            wget -O argocd-vault-plugin
            https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v${AVP_VERSION}/argocd-vault-plugin_${AVP_VERSION}_linux_amd64 &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/ &&
            wget -O argocd-hasadna-plugin
            https://raw.githubusercontent.com/hasadna/hasadna-k8s/master/apps/hasadna-argocd/argocd-hasadna-plugin.py &&
            chmod +x argocd-hasadna-plugin &&
            mv argocd-hasadna-plugin /custom-tools/
        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools

      # Not strictly necessary, but required for passing AVP configuration from a secret and for using Kubernetes auth to Hashicorp Vault
      automountServiceAccountToken: true
