{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata: {name: israelproxy}
spec:
  selector:
    matchLabels:
      app: israelproxy
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels: {app: israelproxy}
    spec:
      containers:
      - name: israelproxy
        image: nginx
        ports:
        - containerPort: 80
        resources: {{ .Values.resources }}
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
            readOnly: true
          - name: differ
            mountPath: /differ/data
            readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: israelproxy
        - name: differ
          nfs:
            server: {{ .Values.differNfsServer | quote }}
            path: {{ $.Values.differNfsPath | quote }}
{{ end }}
