{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
data:
  default.conf: |
    server {
        listen 81;
        server_name  _;
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_set_header X-Forwarded-Host obus-splunk.hasadna.org.il;
            include proxypass/obus-splunk;
        }
    }
{{ end }}
