apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: stride-db-backup
spec:
  schedule: {{ .Values.db.backupSchedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: {{ .Values.db.backupImage }}
            resources: {{ .Values.backupResources }}
            env:
              - name: PGPASSWORD
                valueFrom: {"secretKeyRef": {"name":"db", "key":"POSTGRES_PASSWORD"}}
              - name: HOSTNAME
                value: "stride-db"
              - name: USER
                value: postgres
              - name: DB
                value: postgres
              - name: SCHEMA
                value: public
              - name: FILENAME
                value: /mnt/stride_db.sql.gz
            volumeMounts:
              - name: sirirequester
                mountPath: /mnt
                subPath: stride_db_backup
          volumes:
            - name: sirirequester
              nfs:
                server: {{ .Values.nfsServer | quote }}
                path: {{ .Values.siriRequesterNfsPath | quote }}
