apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: oknesset
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: oknesset
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/OriHoch/knesset-data-k8s.git
