apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: budgetkey
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: budgetkey
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/OpenBudget/budgetkey-k8s.git
