apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dear-diary
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: dear-diary
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/hasadna/hasadna-k8s.git
