apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: odata
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: odata
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/hasadna/hasadna-k8s.git
