{{ if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysadna
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: mysadna
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: mysadna
        image: {{ .Values.image | default "uumpa/hasadna-mysadna" | quote }}
        resources: {"requests": {"cpu": "50m", "memory": "50Mi"}, "limits": {"memory": "100Mi"}}
        ports:
        - containerPort: 80
{{ end }}
