{{ if and .Values.enabled .Values.ingresses }}
{{ range .Values.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  rules:
  {{ range .rules }}
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
  {{ end }}
---
{{ end }}
{{ end }}
