apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ng-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
  - host: {{ .Values.ngAppIngress.host }}
    http:
      paths:
      - path: /static
        backend:
          serviceName: ng-nginx
          servicePort: 80
      - path: /
        backend:
          serviceName: ng-web
          servicePort: 80
  tls:
  - hosts:
    - {{ .Values.ngAppIngress.host }}
    secretName: ng-app-cert
