anyway:
  enabled: true
  enableSecondaries: true
  secondaryReplicas: 3
  nginxForwardedHost: "www.anyway.co.il"
  nginxForwardedScheme: "https"
  mountGoogleApplicationCredentialsSecret: true
  mainResources: '{"requests": {"cpu": "25m", "memory": "684Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
  secondariesResources: '{"requests": {"cpu": "25m", "memory": "933Mi"}, "limits": {"cpu": "78m", "memory": "1500Mi"}}'
  dbResources: '{"requests": {"cpu": "25m", "memory": "2062Mi"}, "limits": {"cpu": "165m", "memory": "3500Mi"}}'
  nginxResources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'
  dbNfsServer: "172.16.0.9"
  dbNfsPath: "/anyway/db"
  DBDUMP_S3_FILE_PREFIX: ""
  dbBackupEnabled: true
  dbBackupSchedule: "10 0 * * *"
  enableLogs: true
  dbNodeSelector: hasadna-worker1
  dbHostPort: 28733

  reports:
    enabled: true
    replicas: 1
    resources: '{"requests": {"cpu": "25m", "memory": "256Mi"}, "limits": {"cpu": "78m", "memory": "500Mi"}}'

  ingresses:
    - name: nginx
      ssl: true
      rules:
        - host: www.anyway.co.il
          serviceName: nginx
          servicePort: 80
        - host: reports.anyway.co.il
          serviceName: reports
          servicePort: 80
    - name: redirect
      ssl: true
      permanentRedirect: https://www.anyway.co.il
      rules:
        - host: anyway.co.il
          serviceName: nginx
          servicePort: 80
        - host: www.oway.org.il
          serviceName: nginx
          servicePort: 80
        - host: oway.org.il
          serviceName: nginx
          servicePort: 80

  vertical_pod_autoscalers:
  - apiVersion: apps/v1
    kind: deployment
    name: anyway-main
  - apiVersion: apps/v1
    kind: deployment
    name: reports
  - apiVersion: apps/v1
    kind: deployment
    name: anyway-secondaries
  - apiVersion: apps/v1
    kind: deployment
    name: db
  - apiVersion: apps/v1
    kind: deployment
    name: nginx