anyway:
  enabled: true
  enableSecondaries: true
  secondaryReplicas: 1
  nginxForwardedHost: "www.anyway.co.il"
  nginxForwardedScheme: "https"
  mountGoogleApplicationCredentialsSecret: true
  mainResources: '{"requests": {"cpu": "150m", "memory": "1000Mi"}, "limits": {"memory": "1500Mi"}}'
  secondariesResources: '{"requests": {"cpu": "100m", "memory": "700Mi"}, "limits": {"memory": "1000Mi"}}'
  dbResources: '{"requests": {"cpu": "300m", "memory": "500Mi"}, "limits": {"memory": "1000Mi"}}'
  nginxResources: '{"requests": {"cpu": "100m", "memory": "100Mi"}, "limits": {"memory": "500Mi"}}'
  dbNfsServer: "172.16.0.9"
  dbNfsPath: "/anyway/db"
  DBDUMP_S3_FILE_PREFIX: ""
  dbBackupEnabled: true
  dbBackupSchedule: "10 0 * * *"
  enableLogs: true
  dbNodeSelector: hasadna-worker1
  dbHostPort: 28733
  ingresses:
    - name: nginx
      ssl: true
      rules:
        - host: www.anyway.co.il
          serviceName: nginx
          servicePort: 80
    - name: redirect
      ssl: true
      permanentRedirect: https://www.anyway.co.il
      rules:
        - host: anyway.co.il
          serviceName: nginx
          servicePort: 80
        - host: www.oway.org.il
          serviceName: nginx
          servicePort: 80
        - host: oway.org.il
          serviceName: nginx
          servicePort: 80
