{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: israelproxy
data:
  default.conf: |
    server {
        listen 80;
        server_name  _;
        location /gisweb-azureedge-net/ {
            proxy_pass https://gisweb.azureedge.net/;
            proxy_set_header Host gisweb.azureedge.net;
        }
    }
    server {
        listen 80;
        server_name differ.odata.org.il;
        location / {
          root /differ/data;
          index null;
          autoindex on;
        }
    }
{{ end }}
