{{ if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nfs-node-initializer
  labels:
    app: nfs-node-initializer
spec:
  selector:
    matchLabels:
      app: nfs-node-initializer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nfs-node-initializer
    spec:
      volumes:
      - name: root-mount
        hostPath:
          path: /
      initContainers:
      - image: ubuntu:18.04
        name: node-initializer
        command:
          - bash
          - "-c"
          - |
            chroot /root apt-get update &&\
            chroot /root apt-get install -y nfs-common
        securityContext:
          privileged: true
        volumeMounts:
        - name: root-mount
          mountPath: /root
      containers:
      - image: "gcr.io/google-containers/pause:2.0"
        name: pause
{{ end }}