{{ if and .Values.enabled .Values.enableNfsServerDeployment }}
apiVersion: v1
kind: Service
metadata:
  name: nfs
spec:
  clusterIP: {{ .Values.nfsServer | quote }}
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs
{{ end }}
