{{ if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-nginx
data:
  default.conf: |
    server {
        listen 80;
        server_name  _;
        location / {
            root /covid19israel;
            index null;
            autoindex on;
        }
    }
{{ end }}
