{{ if and .Values.enabled .Values.enableNfsServerDeployment }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfs
spec:
  selector:
    matchLabels:
      app: nfs
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs
    spec:
      containers:
      - name: nfs
        image: gcr.io/google_containers/volume-nfs:0.8
        args: ["/exports"]
        resources: {"requests": {"cpu": "500m", "memory": "1Gi"}, "limits": {"cpu": "500m", "memory": "1Gi"}}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - name: exports
            mountPath: /exports
      volumes:
        - name: exports
          gcePersistentDisk:
            pdName: {{ .Values.pipelinesCovid19IsraelPersistentDiskName | quote }}
{{ end }}
