apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: cluster-logs-kibana
  namespace: default
spec:
  count: 1
  elasticsearchRef:
    name: cluster-logs
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  version: 7.5.2
