apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluster-logs
  namespace: default
spec:
  http:
    service:
      spec: {}
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - config:
      node.data: true
      node.ingest: true
      node.master: true
      node.store.allow_mmap: false
    count: 1
    name: default
    podTemplate:
      metadata: {}
      spec:
        volumes:
        - name: elasticsearch-data
          nfs:
            path: /elasticsearch-data-cluster-logs
            server: 172.16.0.9
  updateStrategy:
    changeBudget: {}
  version: 7.5.2