apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
spec:
  selector:
    matchLabels:
      app: bot
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: bot
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: leafy
      initContainers: {{- include "app.waitForMigrations" . | nindent 6 }}
      containers:
      - name: bot
        image: {{ .Values.appImage }}
        args: ["bot"]
        resources: {{ toYaml .Values.bot.resources | nindent 10 }}
        env: {{- include "app.common.env" . | nindent 6 }}
        - name: TELEGRAM_TOKEN
          valueFrom: {"secretKeyRef":{"name":"app", "key":"TELEGRAM_TOKEN"}}
