apiVersion: v1
kind: ServiceAccount
metadata:
  name: leafy
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leafy
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [list, get]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leafy
subjects:
- kind: ServiceAccount
  name: leafy
roleRef:
  kind: Role
  name: leafy
  apiGroup: rbac.authorization.k8s.io
