{{ if .Values.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-admin
spec:
  selector:
    matchLabels:
      name: cluster-admin
  template:
    metadata:
      labels:
        name: cluster-admin
    spec:
      volumes:
        - name: host-sys
          hostPath:
            path: /sys
      initContainers:
      - name: sysctl-conf
        image: busybox:1.26.2
        command: ["sh", "-c", "sysctl -w vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: disable-hugepages
        image: busybox:1.26.2
        volumeMounts:
          - name: host-sys
            mountPath: /host-sys
        command: ["sh", "-c", "echo never > /host-sys/kernel/mm/transparent_hugepage/enabled"]
        securityContext:
          privileged: true
      containers:
      - name: pause
        image: busybox:1.26.2
        command: ["sh", "-c", "while true; do sleep 86400; done"]
        resources:
          requests:
            cpu: 1m
            memory: 5Mi
{{ end }}
