airflowImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:v0.0.26
airflowImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:7366de7bbcc490962fd46a9f0440807ed7750c15
anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-7ae5218
dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-e774bc0
dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-e774bc0
etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
etlNginxImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:v0.0.26
etlNginxImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:7366de7bbcc490962fd46a9f0440807ed7750c15
image: docker.pkg.github.com/hasadna/anyway/anyway:sha-e774bc0
imageDev: docker.pkg.github.com/hasadna/anyway/anyway:sha-d7c9707
nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-e774bc0
nginxImageDev: docker.pkg.github.com/hasadna/anyway/nginx:sha-d7c9707
