airflowImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:v.0.0.34
airflowImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-airflow:b5b0dff6fdeb6ce4c32dae54764357b63106568e
anywayReportsImage: docker.pkg.github.com/hasadna/anyway-reports/anyway-reports:sha-3dc1cf4
dbBackupImage: docker.pkg.github.com/hasadna/anyway/db_backup:sha-2648d4c
dbImage: docker.pkg.github.com/hasadna/anyway/db:sha-2648d4c
etlImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl:55a7c1ddb4610b2f75f88db8615f373b62c9f226
etlNginxImage: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:v.0.0.34
etlNginxImageDev: docker.pkg.github.com/hasadna/anyway-etl/anyway-etl-nginx:b5b0dff6fdeb6ce4c32dae54764357b63106568e
image: docker.pkg.github.com/hasadna/anyway/anyway:sha-2648d4c
imageDev: docker.pkg.github.com/hasadna/anyway/anyway:sha-ec6949f
nginxImage: docker.pkg.github.com/hasadna/anyway/nginx:sha-2648d4c
nginxImageDev: docker.pkg.github.com/hasadna/anyway/nginx:sha-ec6949f
