apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  sso: |
    issuer: https://argocd.hasadna.org.il/api/dex
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://argo.hasadna.org.il/oauth2/callback
    scopes:
     - groups
     - email
     - profile
     - roles
    rbac:
      enabled: true
