{{ if .Values.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nfs
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs
      # annotations:
      #   checksum/config: { include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }
    spec:
      containers:
      - name: nfs
        image: k8s.gcr.io/volume-nfs:0.8
        resources: {"requests": {"cpu": "20m", "memory": "50Mi"}}
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: exports
      volumes:
        - name: exports
          {{ if .Values.gcePersistentDiskName }}
          gcePersistentDisk:
            pdName: {{ .Values.gcePersistentDiskName | quote }}
          {{ else }}
          emptyDir: {}
          {{ end }}
{{ end }}
