projects:

  - name: openbus
    spec:
      destinations:
        - name: '*'
          namespace: openbus
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: betaknesset
    spec:
      destinations:
        - name: '*'
          namespace: betaknesset
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: odata
    spec:
      destinations:
        - name: '*'
          namespace: odata
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: datacity
    spec:
      destinations:
        - name: '*'
          namespace: datacity
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: openpension
    spec:
      destinations:
        - name: '*'
          namespace: openpension
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: reportit
    spec:
      destinations:
        - name: '*'
          namespace: reportit
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/hasadna-k8s.git'

  - name: migdar
    spec:
      destinations:
        - name: '*'
          namespace: migdar
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/hasadna/migdar-k8s.git'

  - name: oknesset
    spec:
      destinations:
        - name: '*'
          namespace: oknesset
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/OriHoch/knesset-data-k8s.git'

  - name: budgetkey
    spec:
      destinations:
        - name: '*'
          namespace: budgetkey
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - 'https://github.com/OpenBudget/budgetkey-k8s.git'

apps:

  - name: cluster-admin
    project: default
    destinationNamespace: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/cluster-admin
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: openbus
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/openbus
      helm:
        valueFiles:
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: betaknesset
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/betaknesset

  - name: odata
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/odata
      helm:
        valueFiles:
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: datacity
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/datacity
      helm:
        valueFiles:
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: openpension
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/openpension
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: redash
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/redash
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: reportit
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/reportit
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: resourcesaver
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/resourcesaverproxy
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: vault
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/vault
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: wordpress
    project: default
    source:
      repoURL: 'https://github.com/hasadna/hasadna-k8s.git'
      targetRevision: master
      path: apps/wordpress
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: migdar
    source:
      repoURL: 'https://github.com/hasadna/migdar-k8s.git'
      targetRevision: master
      path: apps/migdar
      helm:
        valueFiles:
          - values-global.yaml
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: oknesset-nginx
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/nginx
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: oknesset-pipelines
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/pipelines
      helm:
        valueFiles:
          - values-hasadna.yaml
          - values-hasadna-auto-updated.yaml

  - name: oknesset-publicdb
    project: oknesset
    destinationNamespace: oknesset
    source:
      repoURL: 'https://github.com/OriHoch/knesset-data-k8s.git'
      targetRevision: master
      path: apps/publicdb
      helm:
        valueFiles:
          - values-hasadna.yaml

  - name: budgetkey
    source:
      repoURL: 'https://github.com/OpenBudget/budgetkey-k8s.git'
      targetRevision: master
      path: .
      helm:
        valueFiles:
          - values-global.yaml
          - values-hasadna.yaml
          - values.auto-updated.yaml
