apiVersion: v1
kind: ConfigMap
metadata:
  name: redirector-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        return 200 'OK';
      }
    }
