enabled: true
adminerEnabled: false
dockerDaemonConfig:
  "log-driver": "json-file"
  "log-opts":
    "max-size": "100m"
    "max-file": "5"
    "compress": "true"

terraformStateDb:
  nodePort: 32162
  resources:
    requests:
      memory: 250Mi
      cpu: 50m
    limits:
      memory: 500Mi
      cpu: 100m
  nfsServer: "~iac:hasadna_nfs1_internal_ip~"
  nfsPath: "/terraform/state_db"

secrets:
  - name: terraform-state-db
    data:
      POSTGRES_PASSWORD: "~vault:Projects/k8s/terraform:state_db_password~"
