israelproxy:
  enabled: true
  differNfsServer: "172.16.0.9"
  differNfsPath: "/israelproxy/differ/data"
  ingresses:
    - name: israelproxy
      rules:
        - host: israelproxy.odata.org.il
          serviceName: israelproxy
          servicePort: 80
        - host: differ.odata.org.il
          serviceName: israelproxy
          servicePort: 80
