odata:
  enabled: true
  ckanDeploymentEnabled: true
  ckanResources: '{}'
  dbResources: '{}'
  solrResources: '{}'
#  ckanDataPersistentDiskName: odata-ckan-data
#  ckanDbPersistentDiskName: odata-db
#  nfsEnabled: true
#  nfsGcePersistentDiskName: odata-ckan-data-nfs
  ckanDataNfsServer: 10.100.17.164
#  etcCkanDefaultSecretName: ckan-default-3
  ckanSecretName: ckan-secrets
  envVarsSecretName: env-vars
#  dbNfsEnabled: true
#  ckanDbNfsServer: 10.100.195.176
  replicas: 1
  redisResources: '{}'
  ckanJobsEnabled: true
  ckanJobsPortForward: true
  ckanJobsDbResources: '{}'
  ckanJobsDbTerminationGracePeriodSeconds: 1
  ckanJobsResources: '{}'

  db:
    terminationGracePeriodSeconds: 1
    image: orihoch/data4dappl-db:v0.2.16
    opsImage: orihoch/data4dappl-db-ops:v0.2.15

  datastore:
    enabled: true
#    initialize: true
    terminationGracePeriodSeconds: 1
    datapusherEnabled: false
    xloaderEnabled: true
    image: orihoch/data4dappl-db:v0.2.15
    opsImage: orihoch/data4dappl-db-ops:v0.2.15
    resources: '{}'
    dbOps:
      enabled: false
#      backup: "gs://odata-k8s-backups/production/blue/datastore-db-dump-"
  #    restore: "gs://odata-k8s-backups/production/datastore-db-dump-2018-09-27.datastore.dump"
    # this is needed when connecing to ckan using port-forward
    datapusherPortForward: true
    dataPusherTerminationGracePeriodSeconds: 1
    dataPusherResources: '{}'
#    persistentDiskName: odata-blue-datastore

  dbOps:
    enabled: false
#    backup: "gs://odata-k8s-backups/testing/ckan-db-dump-"
#    restore: "gs://odata-k8s-backups/production/ckan-db-dump-2018-09-24.ckan.dump"

  solrImage: orihoch/solr-ckan-2.8.1:3

  pipelines:
    # pipelines require a shared directory with the ckan server
    # this requires ckanDataNfsServer to be set as well
#    enabled: true
    resources: '{}'
    terminationGracePeriodSeconds: 1
    sysadminUser: pipelines-sysadmin
    sysadminEmail: pipelines-sysadmin@localhost
    secretName: pipelines-sysadmin
    manual: true

  siteUrl: http://localhost:5000
  siteTitle: מידע ממשלתי לעם - סביבת פיתוח מקומית
  siteLogo: /base/images/ckan-logo.png
  siteDescription: סביבת פיתוח מקומית - נתוני בדיקות
  displayTimezone: Asia/Jerusalem
  favIcon: /base/images/ckan.ico
  localeDefault: he
  localeOrder: he en ar
  localesOffered: he en ar
  localesFilteredOut: ""

  ckanPlugins: >
    stats text_view image_view recline_view
    odata_org_il file_uploader_ui datapackage_pipelines upload_via_email
    datastore xloader

  uploadViaEmail:
#    default_sender_to_address: ckan.co.il@gmail.com
#    default_sender_organization_id: anonymous-email-senders
    success_message: The dataset is available at {dataset_url}
#    success_message_from_email: odata.org.il+donotreply@gmail.com
    success_message_subject: Your dataset was created successfully

  auth:
    anon_create_dataset: "false"
    create_unowned_dataset: "false"
    create_dataset_if_not_in_organization: "true"
    user_create_groups: "false"
    user_create_organizations: "false"
    user_delete_groups: "false"
    user_delete_organizations: "false"
    create_user_via_api: "false"
    create_user_via_web: "true"
    roles_that_cascade_to_sub_groups: "admin"
