apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-monitoring-system
  labels:
    name: rancher
spec:
  ports:
  - port: 9796
    targetPort: 9796
  type: ExternalName
  externalName: ~iac:rancher_ip~
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rancher
  namespace: cattle-monitoring-system
spec:
  selector:
    matchLabels:
      name: rancher
  endpoints:
  - port: "9796"
