name: ci
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      fake_commit_message:
        description: 'fake commit message to use for the manual trigger, if empty uses the actual commit message'
        required: true
        default: ''
env:
  RANCHER_KUBECONFIG: ${{ secrets.RANCHER_KUBECONFIG }}
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        pushd `mktemp -d` &&\
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.16.7/bin/linux/amd64/kubectl" &&\
        chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl &&\
        popd &&\
        bash apps_travis_script.sh install_helm &&\
        bash helm_lint_all.sh &&\
        COMMIT_MSG="${{ github.event.inputs.fake_commit_message }}" &&\
        if [ "${COMMIT_MSG}" == "" ]; then
          COMMIT_MSG="$(git log -1 --pretty=format:"%s")"
        fi &&\
        echo "${RANCHER_KUBECONFIG}" > .rancher.kubeconfig &&\
        KUBECONFIG=.rancher.kubeconfig kubectl get nodes >/dev/null &&\
        KUBECONFIG=.rancher.kubeconfig kubectl version &&\
        if ./kubectl_patch_charts.py "${COMMIT_MSG}" --dry-run; then
          echo performing patches &&\
          if ./kubectl_patch_charts.py "${COMMIT_MSG}"; then
            echo patches successful && exit 0
          else
            echo failed patches && exit 1
          fi
        else
          PATCH_RES=$? &&\
          if [ "${PATCH_RES}" == "1" ]; then
            echo patches dry run failed && exit 1
          fi
          if [ "${PATCH_RES}" == "2" ]; then
            echo nothing to do... && exit 0
          else
            echo invalid patches exit code $PATCH_RES && exit 1
          fi
        fi
