name: ci
on:
  push:
    branches:
      - master
env:
  RANCHER_KUBECONFIG: ${{ secrets.RANCHER_KUBECONFIG }}
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
        bash apps_travis_script.sh install_helm &&\
        bash helm_lint_all.sh &&\
        COMMIT_MSG="$(git log -1 --pretty=format:"%s")" &&\
        pushd `mktemp -d` &&\
        curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" &&\
        chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl &&\
        popd &&\
        echo "${RANCHER_KUBECONFIG}" > .rancher.kubeconfig &&\
        KUBECONFIG=.rancher.kubeconfig kubectl get nodes >/dev/null &&\
        if ./kubectl_patch_charts.py "${COMMIT_MSG}" --dry-run; then
          echo performing patches &&\
          if ./kubectl_patch_charts.py "${COMMIT_MSG}"; then
            echo patches successful && exit 0
          else
            echo failed patches && exit 1
          fi
        else
          PATCH_RES=$? &&\
          if [ "${PATCH_RES}" == "1" ]; then
            echo patches dry run failed && exit 1
          fi
          if [ "${PATCH_RES}" == "2" ]; then
            echo nothing to do... && exit 0
          else
            echo invalid patches exit code $PATCH_RES && exit 1
          fi
        fi
