name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: |
      bash apps_travis_script.sh install_helm &&\
      bash helm_lint_all.sh
