{{ if and .Values.enabled .Values.ckanDeploymentEnabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: ckan}
spec:
  {{ if .Values.ckanDataNfsServer }}
  replicas: 2
  {{ else }}
  replicas: 1
  strategy:
    type: Recreate
  {{ end }}
  revisionHistoryLimit: 2
  template:
    metadata:
      labels: {app: ckan}
    spec:
      containers:
      - name: ckan
        image: {{ .Values.ckanImage | default "gcr.io/uumpa-public/data4dappl-ckan@sha256:c6f9c390f26da7b907aa54394224c04a191c11e1f36b694f1bc58e7eb95cf7b5" | quote }}
        ports:
        - {containerPort: 5000}
        resources: {{ .Values.ckanResources }}
        volumeMounts:
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: ckan}
        - {mountPath: /etc/ckan/default, name: etc-ckan-default, readOnly: true}
      volumes:
      - name: etc-ckan-default
        secret:
          secretName: {{ .Values.etcCkanDefaultSecretName | default "etc-ckan-default" }}
      - name: ckan-data
        {{ if .Values.ckanDataNfsServer }}
        nfs:
          server: {{ .Values.ckanDataNfsServer }}
          path: "/"
        {{ else if .Values.ckanDataPersistentDiskName }}
        gcePersistentDisk:
          pdName: {{ .Values.ckanDataPersistentDiskName | quote }}
        {{ else }}
        emptyDir: {}
        {{ end }}
{{ end }}
