{{ if .Values.dbNfsEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: db-nfs
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: dbNfs
{{ end }}
