{{ if and .Values.enabled .Values.pipelines.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata: {name: pipelines}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels: {app: pipelines}
    spec:
      serviceAccountName: {{ .Values.ckanServiceAccountName | quote }}
      {{ if .Values.pipelines.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.pipelines.terminationGracePeriodSeconds }}
      {{ end }}
      initContainers:
      - name: initialize
        image: orihoch/data4dappl-kubectl:v0.2.2
        command: [bash, "-c", "./kubectl.sh initialize-pipelines $PIPELINES_SYSTEMIN_USER $PIPELINES_SYSADMIN_EMAIL $PIPELINES_SECRET_NAME"]
        env:
        - name: PIPELINES_SYSTEMIN_USER
          value: {{ .Values.pipelines.sysadminUser | default "pipelines-sysadmin" | quote }}
        - name: PIPELINES_SYSADMIN_EMAIL
          value: {{ .Values.pipelines.sysadminEmail | default "pipelines-sysadmin@ckan" | quote }}
        - name: PIPELINES_SECRET_NAME
          value: {{ .Values.pipelines.secretName | default "pipelines" | quote }}
      containers:
      - name: pipelines
        image: orihoch/datapackage-pipelines-ckanext:v0.0.4
        {{ if not .Values.pipelines.manual }}
        args:
        - "server"
        {{ end }}
        env:
        - name: CKAN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.pipelines.secretName | default "pipelines" | quote }}
              key: apikey
        - name: CKAN_URL
          value: {{ .Values.pipelines.ckanUrl | default "http://ckan:5000" | quote }}
        - name: DPP_REDIS_HOST
          value: "127.0.0.1"
        
        {{ if .Values.pipelines.manual }}
        - name: MANUAL_PIPELINES
          value: "yes"
        {{ else }}
        - name: DPP_CELERY_BROKER
          value: "redis://localhost:6379/6"
        {{ end }}
        ports:
        - {containerPort: 5050}
        resources: {{ .Values.pipelines.resources }}
        volumeMounts:
        - {mountPath: /pipelines, name: ckan-data, subPath: pipelines}
        - {mountPath: /var/lib/ckan, name: ckan-data, subPath: ckan}
        - {mountPath: /var/redis, name: ckan-data, subPath: pipelines-redis}
      volumes:
      - name: ckan-data
        {{ if .Values.hostPath }}
        hostPath:
          path: {{ .Values.hostPath | quote }}
          type: DirectoryOrCreate
        {{ else }}
        nfs:
          server: {{ .Values.ckanDataNfsServer | default "nfs" | quote }}
          path: "/"
        {{ end }}
{{ end }}
