{{ if .Values.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - image: {{ .Values.solrImage | quote }}
        name: solr
        ports:
        - containerPort: 8983
        resources: {{ .Values.solrResources }}
{{ end }}
